name: Build Xiaomi Pad 5 (nabu) (DerpFest A15)

on:
  workflow_call:
  workflow_dispatch:

env:
  # Device env
  DEVICE_NAME : "Xiaomi Pad 5"
  DEVICE_CODENAME : "nabu"

  CUSTOM_CMDS : "CLANG_TRIPLE=aarch64-linux-gnu-"
  EXTRA_CMDS : "LD=ld.lld LLVM=1 LLVM_IAS=1"

  KERNEL_SOURCE : "https://github.com/goodmorningwsad-afk/kernel_xiaomi_nabu-ki"
  KERNEL_BRANCH : "derp15.1"

  CLANG_SOURCE : "https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/LLVM-19.1.7-Linux-X64.tar.xz"
  CLANG_BRANCH : ""

  GCC_GNU : false
  GCC_64_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git"
  GCC_64_BRANCH : "android12L-release"
  GCC_32_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9.git"
  GCC_32_BRANCH : "android12L-release"

  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME : "vendor/xiaomi/nabu_inflated_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false

  KERNELSU_SOURCE : ""
  KERNELSU_BRANCH : ""

  KERNELSU_AUTO_GET : "true" 
  KERNELSU_AUTO_FORK : "sukisu" 

  SUSFS_ENABLE : "false"
  SUSFS_FIXED : "false"

  AK3_SOURCE : "https://github.com/osm0sis/AnyKernel3.git"
  AK3_BRANCH : "master"

  BOOT_SOURCE : ""

  NEED_DTBO : "false"
  NEED_SAFE_DTBO : "false"

  ROM_TEXT : "derpfest_a15"

  # Other env - 锁定 Python 2 拯救老内核
  PYTHON_VERSION: "2" 

  PACK_METHOD: "Anykernel3" 

  KERNELSU_METHOD: "shell" 

  PATCHES_SOURCE: "author/source" 
  PATCHES_BRANCH: "branch" 

  SUSFS_FOLDER_FIXED: "" 
  SUSFS_PATCH_FIXED: "" 

  REKERNEL_ENABLE: "false" 

  HOOK_METHOD: "syscall" 
  HOOK_OLDER: "false" 

  KERNEL_PATCH: "false" 

  KPM_ENABLE: "true" 
  KPM_INLINE: "true" 
  KPM_KPATCH_NEXT: "false" 
  KPM_PATCH_SOURCE: "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU_patch/refs/heads/main/kpm/patch_linux" 

  BASEBAND_GUARD_ENABLE: "false" 
  BASEBAND_GUARD_BOOT: "false" 

  HIDE_STUFF: "false" 

  GENERATE_DTB: "false" 
  GENERATE_CHIP: "qcom" 

  BUILD_DEBUGGER: "false" 
  SKIP_PATCH: "false" 

  BUILD_OTHER_CONFIG: "false" 
  MERGE_CONFIG_FILES: "vendor/debugfs.config,vendor/lahaina_QGKI.config"

  FREE_MORE_SPACE: "false" 

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-latest 
    container: ubuntu:focal
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: ⏰ Checkout repository
        uses: actions/checkout@v4

      - name: ⌛️ Compilation environment preparation
        uses: ./.github/workflows/build-env

      - name: ⚙️ Get neccssary tools
        uses: ./.github/workflows/build-ready

      - name: 🪝 Patch Kernel of SUSFS
        uses: ./.github/workflows/patch-susfs

      - name: 🔗 Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe

      - name: 🪛 Extra Kernel Options
        run: |
          cd $GITHUB_WORKSPACE/device_kernel
          # 屏蔽闲置报错
          echo "ccflags-y += -Wno-unused-function" >> fs/Makefile
          echo "ccflags-y += -Wno-error" >> fs/Makefile

      - name: 🧰 Patch Kernel of Re:Kernel
        uses: ./.github/workflows/patch-rekernel

      - name: 🔒 Patch Kernel of Baseband Guard
        uses: ./.github/workflows/patch-baseband-guard

      - name: 🔧 Patch Hide Stuff
        uses: ./.github/workflows/patch-hide-stuff

      - name: 🚀 Build Process
        uses: ./.github/workflows/build-process

      - name: 🔩 Pack Process
        uses: ./.github/workflows/pack-process

      - name: ✏️ Upload Artifacts
        uses: ./.github/workflows/upload-files
